branches:
  only:
  - master
  - develop
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: 7
      env: BUILD_TYPE=ios NPM=6.9.0 NODE=10.16.0 CORDOVA=9.0.0 IONIC=4.12.0 FULL_BUILD=1 IONIC_NATIVE=4.7.0 PRELOAD_PLUGINS=1
    - os: linux
      language: android
      node_js: 7
      env: BUILD_TYPE=android NPM=6.9.0 NODE=10.16.0 CORDOVA=9.0.0 IONIC=4.12.0 FULL_BUILD=1 IONIC_NATIVE=4.7.0 PRELOAD_PLUGINS=1
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28

before_install:
- printenv
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update > /dev/null;
    brew upgrade;
    brew install jq;
    gem install --no-document cocoapods:1.5.3;
    pod repo update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    uname -a;
    nvm --version;
    nvm install $NODE;
    nvm alias default 9;
    nvm list;
    export PATH=/usr/lib/ccache:$PATH;
    which g++;
    fi
install:
  - npm i -g npm@$NPM cordova@$CORDOVA ionic@$IONIC
  
before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis/addkeys.sh ; fi
script:
- yarn install
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis/build-ios.sh && ./travis/package-ios.sh ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/build-android.sh && ./travis/package-android.sh ; fi
env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
deploy:
  provider: releases
  github-token: $GITHUB_TOKEN
  file_glob: true
  file: output/*
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
  local_dir: www